apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: labteam
resources:
- ../../k8s
images:
- name: docker-registry.mydomain/lab/happysct
  newTag: stable
patches:
- path: deployment.yaml