apiVersion: v1
kind: Service
metadata:
  labels:
    app: happysct
  name: happysct
  namespace: labteam
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: happysct
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None